name: Build Framework

on:
  push:
    paths:
      - packages/framework/**
  workflow_dispatch:

jobs:
  build:
    name: Test Framework Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter framework... install

      - name: Build framework
        run: pnpm exec lerna run build --scope=@nyx-discord/framework
