name: Build Core

on:
  push:
    paths:
      - packages/core/**
  workflow_dispatch:

jobs:
  build:
    name: Test Core Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter core install

      - name: Build core
        run: pnpm exec lerna run build --scope=@nyx-discord/core
