name: Run Jest Tests

on:
  push:
    paths:
      - packages/core/**
      - packages/framework/**
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build core
        run: pnpm build:core

      - name: Test core
        run: pnpm run test:core

      - name: Build framework
        run: pnpm build:framework

      - name: Test framework
        run: pnpm run test:framework
